#!/bin/sh

set -e

PHPVIRTUALBOX_DIR=/usr/share/phpvirtualbox

case "$1" in
    configure)
        chown -R openmediavault:openmediavault ${VIRTUALBOX_DIR}
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
