#!/bin/sh

set -e

PHPVIRTUALBOX_DIR=/usr/share/phpvirtualbox

case "$1" in
    configure)
        find "${PHPVIRTUALBOX_DIR}" -type d -exec chmod 644 {} +
        find "${PHPVIRTUALBOX_DIR}" -type f -exec chmod 755 {} +
        chown -R www-data:www-data ${PHPVIRTUALBOX_DIR}
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

# Don't use DEBHELPER here at the moment since we don't want to enable
# vboxinit by default. We still want to stop and disable it though.

exit 0
